---
- name: Create Users & Groups
  hosts: server-2
  gather_facts: false
  become: true
  vars:
    - default_user_password: pass123

  tasks:
    - name: Create group
      group:
        name: admin_group
        state: present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512','A512') }}"
        shell: /bin/bash
        group: admin_group
      loop:
        - sam
        - jessica
        - shandy